#spring.application.name=day03

#server.port=8888
server:
  port: 1111

# MySQL
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb
#spring.datasource.username=test
#spring.datasource.password=1212

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/testdb
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:log4jdbc:mysql://localhost:3306/testdb
    username: test
    password: 1212


# mybatis mapper
#mybatis.mapper-locations=classpath:mapper/*.xml
# alias
#  mybatis.type-aliases-package=com.mbc.day03.domain

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mbc.day03.domain

  spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: true  # 프로덕션 환경에서는 캐싱을 사용하는 것이 일반적입니다.